### ISSUE TITLE
The variable JOURNAL:REPLAY-FORCE-INSERT is unbound.

### ISSUE THREAD

**Issue by sabracrolleton** [melisgl/journal#1]
Just tried compiling on sbcl 2.07 and it failed with the error The variable JOURNAL:REPLAY-FORCE-INSERT is unbound.

**Comment by melisgl** [comment]
Ah, thanks. Forgot to push a commit to mgl-pax, which adds the RESTART locative and DEFINE-RESTART macro.
That means you'll need to update mgl-pax too to compile Journal.
Sorry for the inconvenience.

**Comment by melisgl** [comment]
Or you can just comment out the `define-restart replay-force-insert` and the `define-restart replay-force-upgrade` forms.

**Comment by sabracrolleton** [comment]
Thanks.
